### PR TITLE
Historyfix

### PR DESCRIPTION
**Pull request by dhudici**

### CODE REVIEW

**Comment by dhudici** [comment]
Guessing that this project isn't really being supported anymore

**Comment by davetropeano** [comment]
I think what's happened is that we haven't updated/restructed the repositories to reflect newer internal work. After getting some experience talking/working with others on linked data type applications we started using a more JSON based approach instead of the current RDF/JSON hybrid. This reduces a lot of the server code and code in utils.js here. We've also experimented with a rewrite of the persistence mechanism again avoiding the internal RDF usage... but we haven't checked this back in.

**Comment by frankbu** [comment]
The python libraries have been moved to https://github.com/ld4apps/lda-serverlib (ld4apps branch) which is now also available at PyPi (pip install ld4apps).

**Comment by dhudici** [comment]
So what I am understanding is that this pull request has really diverged from the current project after all this time, yes?

**Comment by davetropeano** [comment]
No. More that we refactored and changed some of this code and didn't push the changes back. Also, on the client side the very file you fixed the nav bug in -- utils.js -- we've been using a local variation of (again, not pushed). I actually had a nav issue the other day that your fix addresses. I accepted the changes - thanks.

**Comment by dhudici** [comment]
Ah ok, I was worried about merge conflicts or big functional changes that would void the code changes in this pull request. I tested it originally so I hope things still work and will also work with the local variation. Did you try the changes from this pull request in your environment to see if they fixed the nav issues you were having @davetropeano?

**Pull request merged**
